- import_playbook: management_managementgroups_put.yml


- hosts: localhost
  roles:
    - ../modules
  vars_files:
    - _vars.yml
  vars:
    management_group_name: ChildGroup
  tasks:

    - name: AddSubscriptionToManagementGroup
      azure_rm_managementgroupsubscription:
        group_id: '{{management_group_name}}'
    