---
- hosts: localhost
  vars_files:
    - _vars.yml
  tasks:
    - name: PutManagementGroup
      azure_rm_managementgroup:
        group_id: ChildGroup
        id: /providers/Microsoft.Management/managementGroups/ChildGroup
        type: /providers/Microsoft.Management/managementGroups
        name: ChildGroup
        properties:
          tenantId: '{{tenant_id}}'
          display_name: ChildGroup
          details:
            parent:
              id: /providers/Microsoft.Management/managementGroups/RootGroup
    - name: PatchManagementGroup
      azure_rm_managementgroup:
        group_id: ChildGroup
    - name: DeleteManagementGroup
      azure_rm_managementgroup:
        group_id: ChildGroup
        state: absent
    